### ISSUE TITLE
Make Sign Up page reviewed By Jett

### ISSUE THREAD

**Issue by andrewcomputsci2019** [alextitov19/p1-codingcrocs-tri3#33]
- [x] login HTML page
- [x] navbar login tab
- [x] create sql Database
- [x] connect to sql DataBase
- [x] security config changed

**Comment by andrewcomputsci2019** [comment]
Have security done and some validation but need to work on the HTML side of things now but should very close to finishing

**Comment by andrewcomputsci2019** [comment]
Self Grade: 5/5
Database connected to the website 
user can create accounts and log in with accounts
security config changed to allow the user to access certain parts of the website as a guest
Custom Validation is also used to verify data before it is entered into the database

**Comment by jm1021** [comment]
Login seemed to go ok.  It should just redirect me to login, not make me type it in URL.  Also, I am hoping most of Theme parts of page allow guest as you say.  This certainly looks like work and worthy of 3/3.

Issue Title is confusing with Jett's name in it.  He should just make a comment for his review.
