### ISSUE TITLE
DataBase And Form request API.

### ISSUE THREAD

**Issue by andrewcomputsci2019** [alextitov19/p1-codingcrocs-tri3#67]
Database Setup plus code linking database to the front end.

- [x] construct database with tables setup
- [x] construct SQL statements for data retrieval and inserting
- [x] make API for accessing forms and their content
- [x] AJAX/ASYNC js request for crud operation

a possible similar issue is an API for user bio information.

[TableCreation - Copy.txt](https://github.com/alextitov19/p1-codingcrocs-tri3/files/6581245/TableCreation.-.Copy.txt)
SQL table description

**Comment by bennyherrick** [comment]
did we get the back end code to the website working?

**Comment by alextitov19** [comment]
This is a great ticket, seems like a lot of work to do. Once we get the db set up, we can finish connecting the front end as it is mostly done now.

**Comment by andrewcomputsci2019** [comment]
The db is up all that lef is the ajax and front end design

**Comment by andrewcomputsci2019** [comment]
![Uploading image.png…]()

**Comment by andrewcomputsci2019** [comment]
User can view forums as guest but can not post comments or create a forum them selfs

**Comment by JettKim** [comment]
Nice work, now we just need to have each function operational.
